CREATE DATABASE SwapStyle;
GO
USE SwapStyle;
GO

-- USERS
CREATE TABLE dbo.Users (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  DisplayName NVARCHAR(80) NOT NULL,
  Bio NVARCHAR(500) NULL,
  Location NVARCHAR(120) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- ITEMS
CREATE TABLE dbo.Items (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  OwnerId BIGINT NOT NULL,
  Title NVARCHAR(120) NOT NULL,
  Brand NVARCHAR(80) NULL,
  Size NVARCHAR(20) NULL,
  Category NVARCHAR(40) NULL,
  ItemCondition NVARCHAR(10) NOT NULL DEFAULT 'good', -- new/good/worn
  Description NVARCHAR(800) NULL,
  IsAvailable BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Items_Users FOREIGN KEY (OwnerId) REFERENCES dbo.Users(Id)
);

-- ITEM PHOTOS
CREATE TABLE dbo.ItemPhotos (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  ItemId BIGINT NOT NULL,
  Url NVARCHAR(500) NOT NULL,
  SortOrder INT NOT NULL DEFAULT 0,
  CONSTRAINT FK_ItemPhotos_Items FOREIGN KEY (ItemId) REFERENCES dbo.Items(Id)
);

-- LIKES
CREATE TABLE dbo.ItemLikes (
  UserId BIGINT NOT NULL,
  ItemId BIGINT NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT PK_ItemLikes PRIMARY KEY (UserId, ItemId),
  CONSTRAINT FK_ItemLikes_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
  CONSTRAINT FK_ItemLikes_Items FOREIGN KEY (ItemId) REFERENCES dbo.Items(Id)
);

-- MATCHES (trade context: item_a <-> item_b)
CREATE TABLE dbo.Matches (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  UserAId BIGINT NOT NULL,
  UserBId BIGINT NOT NULL,
  ItemAId BIGINT NOT NULL,
  ItemBId BIGINT NOT NULL,
  Status NVARCHAR(10) NOT NULL DEFAULT 'active', -- active/closed/blocked
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Matches_UserA FOREIGN KEY (UserAId) REFERENCES dbo.Users(Id),
  CONSTRAINT FK_Matches_UserB FOREIGN KEY (UserBId) REFERENCES dbo.Users(Id),
  CONSTRAINT FK_Matches_ItemA FOREIGN KEY (ItemAId) REFERENCES dbo.Items(Id),
  CONSTRAINT FK_Matches_ItemB FOREIGN KEY (ItemBId) REFERENCES dbo.Items(Id)
);

-- MESSAGES
CREATE TABLE dbo.Messages (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  MatchId BIGINT NOT NULL,
  SenderId BIGINT NOT NULL,
  Body NVARCHAR(2000) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Messages_Matches FOREIGN KEY (MatchId) REFERENCES dbo.Matches(Id),
  CONSTRAINT FK_Messages_Users FOREIGN KEY (SenderId) REFERENCES dbo.Users(Id)
);

-- Helpful indexes
CREATE INDEX IX_Items_OwnerId ON dbo.Items(OwnerId);
CREATE INDEX IX_ItemLikes_ItemId ON dbo.ItemLikes(ItemId);
CREATE INDEX IX_Messages_MatchId_CreatedAt ON dbo.Messages(MatchId, CreatedAt);
GO
